TODO_Proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_app.urls')),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = "todo_app"
urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('register/', views.registerPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.index, name="index"),
    path('mark_complete_or_incomplete/<str:pk>/', 
        views.mark_complete_or_incomplete, name='mark_complete_or_incomplete'),
    path('add_task/', views.add_task, name='add_task'),
    path('update_task/<str:pk>', views.update_task, name='update_task'),
    path('delete_task/<str:pk>', views.delete_task, name='delete_task'),
]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    task_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    task_name = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.task_user} : {self.task_name}'

todo_app/forms.py
from django.forms import ModelForm


from .models import Task


class TaskForm(ModelForm):
	class Meta:
		model = Task
		fields = ['task_name']
		

todo_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from .models import Task
from .forms import TaskForm


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('todo_app:index')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            get_user = User.objects.get(username=username)
        except:
            messages.error
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login successful")
            return redirect('todo_app:index')
        else:
            messages.error(request, "Incorrect credentials")

    context = {
        'page': page,
    }
    return render(request, 'todo_app/login_register.html', context)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('todo_app:index')

    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            messages.success(request, "Registration successful")
            return redirect('todo_app:index')
        else:
            messages.error(request, "Unable to register, please use different username")
    context = {
        'form': form,
    }
    return render(request, 'todo_app/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('todo_app:login')

@login_required(login_url="todo_app:login")
def index(request):
    user = request.user
    all_tasks = user.task_set.all()
    in_progress_tasks = all_tasks.filter(is_completed=False)
    completed_tasks = all_tasks.filter(is_completed=True)
    context = {
        'in_progress_tasks': in_progress_tasks,
        'completed_tasks': completed_tasks,
    }
    return render(request, 'todo_app/index.html', context)

@login_required(login_url="todo_app:login")
def mark_complete_or_incomplete(request, pk):
    task = Task.objects.get(id=pk)
    task.is_completed = not task.is_completed
    task.save()
    messages.success(request, "Task status changed")
    return redirect('todo_app:index')
    
@login_required(login_url="todo_app:login")
def add_task(request):
    form = TaskForm()
    if request.method == 'POST':
        task = request.POST.get('task_name')
        Task.objects.create(
            task_user=request.user,
            task_name=task,
            is_completed=False,
        )
        messages.success(request, "Task Added")
        return redirect('todo_app:index')
    context = {
        'form': form
    }
    return render(request, 'todo_app/add_task.html', context)


@login_required(login_url="todo_app:login")
def update_task(request, pk):
    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)
    if request.method =='POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request, "Task Updated")
            return redirect('todo_app:index')
    context = {
        'form': form,
    }
    return render(request, 'todo_app/add_task.html', context)


@login_required(login_url="todo_app:login")
def delete_task(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    messages.info(request, "Task Deleted")
    return redirect('todo_app:index')

todo_app/templates/todo_app/add_task.html
{% extends 'todo_app/base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <input type="submit" class="btn btn-primary" name="">
</form>
{% endblock content %}

todo_app/templates/todo_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Todo - Django</title>
</head>
<body>
    {% include 'todo_app/navbar.html' %}
    <div class="container">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>
    <br>
    <div class="container">
        {% block content %}
    
        {% endblock content %}
    </div>
    


    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

todo_app/templates/todo_app/index.html
{% extends 'todo_app/base.html' %}

{% block content %}

<div class="input-group mb-3">
  <a href="{% url 'todo_app:add_task' %}"><button class='btn btn-primary'>Add Task</button></a>
</div>


<div class="tab">
    <button class="tablinks" onclick="openCity(event, 'in-progress')" id="defaultOpen">In Progress</button>
    <button class="tablinks" onclick="openCity(event, 'completed')">Completed</button>
  </div>
  
  <div id="in-progress" class="tabcontent">
      <table class="table table-sm">
        <div>
          <span>Total Tasks: {{ in_progress_tasks.count }}</span>
        </div>
        <hr>
        {% if in_progress_tasks %}
            <tr>
              <th>Task</th>
              <!-- <th>Created</th> -->
              <th>Mark Complete</th>
              <th>Update</th>
              <th>Remove</th>
            </tr>
            {% for task in in_progress_tasks %}
              <tr>
                <td>{{ task.task_name }}</td>
                <!-- <td>{{ task.date_created }}</td> -->
                <td>
                  <a href="{% url 'todo_app:mark_complete_or_incomplete' task.id %}">
                  <i class="bi bi-check2-square"></i></a>
                </td>
                <td>
                  <a href="{% url 'todo_app:update_task' task.id %}">
                    <i class="bi bi-pen"></i></a>
                </td>
                <td>
                  <a href="{% url 'todo_app:delete_task' task.id %}">
                    <i class="bi bi-trash3-fill"></i></a>
                </td>
              </tr>
            {% endfor %}
        {% else %}
            <p>No tasks available </p>
        {% endif %}
      </table>
  </div>
  
  <div id="completed" class="tabcontent">
    <table class="table table-sm">
      <div>
        <span>Total Tasks: {{ completed_tasks.count }}</span>
      </div>
      <hr>
        {% if completed_tasks %}
            <tr>
              <th>Task</th>
              <!-- <th>Created</th> -->
              <th>Mark Pending</th>
              <th>Update</th>
              <th>Remove</th>
            </tr>
            {% for task in completed_tasks %}
              <tr>
                <td>{{ task.task_name }}</td>
                <!-- <td>{{ task.date_created }}</td> -->
                <td>
                  <a href="{% url 'todo_app:mark_complete_or_incomplete' task.id %}">
                  <i class="bi bi-check2-square"></i></a>
                </td>
                <td>
                  <a href="{% url 'todo_app:update_task' task.id %}">
                    <i class="bi bi-pen"></i></a>
                </td>
                <td>
                  <a href="{% url 'todo_app:delete_task' task.id %}">
                    <i class="bi bi-trash3-fill"></i></a>
                </td>
              </tr>
            {% endfor %}
        {% else %}
            <p>No tasks available </p>
        {% endif %}
      </table>
  </div>

{% endblock content %}

todo_app/templates/todo_app/login_register.html
{% extends 'todo_app/base.html' %}

{% block content %}

{% if page == 'login' %}
<form action="" method="POST">
	{% csrf_token %}
  <!-- Email input -->
  <h3>Login</h3>
  <div class="form-outline mb-4">
    <label class="form-label" for="form2Example1">Username</label>
    <input type="text" name="username" id="form2Example1" class="form-control" 
    placeholder="e.g. rick sanchez"/>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <label class="form-label" for="form2Example2">Password</label>
    <input type="password" name="password" id="form2Example2" class="form-control" 
    placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"/>
  </div>

  <!-- Submit button -->
  <input type="submit" class="btn btn-primary btn-block mb-4" value="Login" >

  <!-- Register buttons -->
  <div class="text-center">
    <p>Not a member? <a href="{% url 'todo_app:register' %}">Register</a></p>

  </div>
</form>

{% else %}
<form action="" method="POST">
	{% csrf_token %}
  <!-- Email input -->
  <h3>Register</h3>
  
  <!-- Register form  -->
  {% for field in form %}
  <div class="form-outline mb-4">
    <label class="form-label" for="form2Example1">{{ field.label }}: </label>
    {{ field  }}
  </div>
  {% endfor %}

  <!-- Submit button -->
  <input type="submit" class="btn btn-primary btn-block mb-4" value="Register" >

  <!-- Register buttons -->
  <div class="text-center">
    <p>Already a member? <a href="{% url 'todo_app:login' %}">Login</a></p>

  </div>
</form>

{% endif %}
{% endblock content %}

todo_app/templates/todo_app/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Todo App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'todo_app:index' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <span class="nav-item">
            <a class="nav-link" href="#">{{ request.user }}</a>
          </span>
          <li class="nav-item right">
            <a class="nav-link" href="{% url 'todo_app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item right">
            <a class="nav-link" href="{% url 'todo_app:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

todo_app/templates/todo_app/old_index.html.html
{% extends 'todo_app/base.html' %}

{% block content %}

{% include 'todo_app/add_task_form.html' %}

<div class="tab">
    <button class="tablinks" onclick="openCity(event, 'in-progress')" id="defaultOpen">In Progress</button>
    <button class="tablinks" onclick="openCity(event, 'completed')">Completed</button>
  </div>
  
  <div id="in-progress" class="tabcontent">
    
    <ul class="list-group">
        {% if in_progress_tasks %}
            {% for task in in_progress_tasks %}
                <li class="list-group-item">{{ task }}
                    <div style="float: right;">
                        <a href="{% url 'todo_app:mark_complete_or_incomplete' task.id %}"><i class="bi bi-check2-square"></i></a>
                        <a href="#"><i class="bi bi-pen"></i></a>
                        <a href="#"><i class="bi bi-trash3-fill"></i></a>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item">-- No tasks Available --</li>
        {% endif %}
      </ul>
  </div>
  
  <div id="completed" class="tabcontent">
    <ul class="list-group">
        {% if completed_tasks %}
            {% for task in completed_tasks %}
                <li class="list-group-item">{{ task }}
                    <div style="float: right;">
                        <a href="{% url 'todo_app:mark_complete_or_incomplete' task.id %}"><i class="bi bi-check2-square"></i></a>
                        <a href="#"><i class="bi bi-pen"></i></a>
                        <a href="#"><i class="bi bi-trash3-fill"></i></a>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item">-- No tasks Available --</li>
        {% endif %}
      </ul>
  </div>

{% endblock content %}